import React, { useEffect, useRef, useState } from 'react';
import { Play, Pause, Download, Volume2, Music4 } from 'lucide-react';
import Button from './Button';
import { base64ToArrayBuffer, createWavBlob } from '../utils/audioUtils';

interface AudioPlayerProps {
  base64Audio: string;
}

const AudioPlayer: React.FC<AudioPlayerProps> = ({ base64Audio }) => {
  const audioRef = useRef<HTMLAudioElement | null>(null);
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const [isPlaying, setIsPlaying] = useState(false);
  const [currentTime, setCurrentTime] = useState(0);
  const [duration, setDuration] = useState(0);
  const [blobUrl, setBlobUrl] = useState<string | null>(null);

  useEffect(() => {
    // Convert base64 to blob URL
    const pcmData = base64ToArrayBuffer(base64Audio);
    const wavBlob = createWavBlob(pcmData);
    const url = URL.createObjectURL(wavBlob);
    setBlobUrl(url);

    return () => {
      URL.revokeObjectURL(url);
    };
  }, [base64Audio]);

  useEffect(() => {
    if (!blobUrl || !canvasRef.current || !audioRef.current) return;

    // Visualizer setup would go here (omitted for brevity, just using animation)
    // For a real visualizer, we'd need an AudioContext and AnalyserNode connected to the audio element.
  }, [blobUrl]);

  const togglePlay = () => {
    if (!audioRef.current) return;
    if (isPlaying) {
      audioRef.current.pause();
    } else {
      audioRef.current.play();
    }
    setIsPlaying(!isPlaying);
  };

  const handleTimeUpdate = () => {
    if (audioRef.current) {
      setCurrentTime(audioRef.current.currentTime);
    }
  };

  const handleLoadedMetadata = () => {
    if (audioRef.current) {
      setDuration(audioRef.current.duration);
    }
  };

  const formatTime = (time: number) => {
    const minutes = Math.floor(time / 60);
    const seconds = Math.floor(time % 60);
    return `${minutes}:${seconds.toString().padStart(2, '0')}`;
  };

  const handleDownload = () => {
    if (blobUrl) {
      const a = document.createElement('a');
      a.href = blobUrl;
      a.download = 'podcast.wav';
      a.click();
    }
  };

  return (
    <div className="bg-gray-900 border border-gray-800 rounded-2xl p-6 shadow-2xl">
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-3">
            <div className="p-3 bg-rose-500/10 rounded-full">
                <Music4 className="text-rose-500" size={24} />
            </div>
            <div>
                <h3 className="font-semibold text-white">Interview Guide Podcast</h3>
                <p className="text-sm text-gray-500">Generated by Gemini</p>
            </div>
        </div>
        <button 
            onClick={handleDownload}
            className="p-2 hover:bg-gray-800 rounded-full transition-colors text-gray-400 hover:text-white"
            title="Download WAV"
        >
            <Download size={20} />
        </button>
      </div>

      {/* Visualizer Placeholder */}
      <div className="h-24 bg-gray-950 rounded-xl mb-6 flex items-center justify-center relative overflow-hidden group">
         <div className="absolute inset-0 flex items-center justify-center gap-1 opacity-50">
            {[...Array(20)].map((_, i) => (
                <div 
                    key={i} 
                    className={`w-1.5 bg-indigo-500 rounded-full transition-all duration-300 ${isPlaying ? 'animate-pulse' : 'h-2'}`}
                    style={{ 
                        height: isPlaying ? `${Math.random() * 80 + 20}%` : '10%',
                        animationDelay: `${i * 0.05}s`
                    }}
                />
            ))}
         </div>
      </div>

      {/* Controls */}
      <div className="flex flex-col gap-4">
        <div className="flex items-center gap-4">
            <span className="text-xs text-gray-400 font-mono w-10">{formatTime(currentTime)}</span>
            <input 
                type="range" 
                min="0" 
                max={duration || 100} 
                value={currentTime} 
                onChange={(e) => {
                    const time = parseFloat(e.target.value);
                    if (audioRef.current) audioRef.current.currentTime = time;
                    setCurrentTime(time);
                }}
                className="flex-1 h-1.5 bg-gray-800 rounded-lg appearance-none cursor-pointer [&::-webkit-slider-thumb]:appearance-none [&::-webkit-slider-thumb]:w-3 [&::-webkit-slider-thumb]:h-3 [&::-webkit-slider-thumb]:rounded-full [&::-webkit-slider-thumb]:bg-white"
            />
            <span className="text-xs text-gray-400 font-mono w-10">{formatTime(duration)}</span>
        </div>

        <div className="flex justify-center">
             <button 
                onClick={togglePlay}
                className="w-14 h-14 bg-white rounded-full flex items-center justify-center text-black hover:scale-105 transition-transform shadow-lg shadow-white/20"
             >
                {isPlaying ? <Pause fill="currentColor" /> : <Play fill="currentColor" className="ml-1" />}
             </button>
        </div>
      </div>

      {blobUrl && (
        <audio 
            ref={audioRef} 
            src={blobUrl} 
            onTimeUpdate={handleTimeUpdate}
            onLoadedMetadata={handleLoadedMetadata}
            onEnded={() => setIsPlaying(false)}
            className="hidden"
        />
      )}
    </div>
  );
};

export default AudioPlayer;
